### ISSUE TITLE
Deshabilitar en lugar de eliminar

### ISSUE THREAD

**Issue by admred** [Grupo13SpringComision23650/ElRepositoryDelGrupo13#10]
En la clase pasada, Cris propuso que deberíamos "deshabilitar" en lugar de borrar el **Usuario**, esto por temas "*legales*" . También lo mismo para la entidad **Account**. 

Así, que estas entidades deberían tener algún atributo extra como *isEnabled* o *status* (el nombre que os guste). 

Otro detalle, antes de dar de baja el usuario se deberían deshabilitar todas las cuentas primero, después deshabilitar el mismo usuario, y en caso que se quiera dar de alta de nuevo, restablecer todas las cuentas ó generarle una cuenta nueva pero acá queda al libre albeldrío de ustedes.

**Comment by Mirtyta** [comment]
Hola a todos en las entidades tanto en User como en Account se generara un nuevo campo llamado Status, el cual nos indicara si la cuenta esta ACTIVO o DESACTIVA, esto lo realizaremos en ambas ENTIDADES,  ya que en User puede que el usuario esté DESACTIVADO y ya no tenga cuenta en el banco,  en ese caso todas sus todas cuentas estaran DESACTIVADAS, o en el caso de que el usuario decida cerrar una de sus cuentas, el User estara HABILITADO, pero la cuenta cerrada estara DESHABITITADA pero podra operar con el resto, es por ello que se agregara el campo STATUS tanto en la entidad USER como en ACCOUNT, para saber en que estado se encuentra cada una. Espero sus comentarios y/o opiniones para saber como seguir.
