### ISSUE TITLE
No aparecen los ficheros de Mirta cuando hace un PR

### ISSUE THREAD

**Issue by admred** [Grupo13SpringComision23650/ElRepositoryDelGrupo13#11]
Hola Mirty, bueno es un error raro, estuve buscando no econtre mucha informacion

### Metodo 1: 
Desde la consola parado en la raiz del proyecto

```
git pull
git checkout mirty
git merge master --allow-unrelated

```
Pero vas a tener que editar a mano los siguientes archivos (ojo que algunos archivos le borraron el contenido)

```
CONFLICTO (agregar/agregar): Conflicto de fusión en mvnw
Auto-fusionando pom.xml
CONFLICTO (agregar/agregar): Conflicto de fusión en pom.xml
Auto-fusionando src/main/java/com/homebanking/grupo13/controllers/TransferController.java
CONFLICTO (agregar/agregar): Conflicto de fusión en src/main/java/com/homebanking/grupo13/controllers/TransferController.java
Auto-fusionando src/main/java/com/homebanking/grupo13/mappers/TransferMapper.java
CONFLICTO (agregar/agregar): Conflicto de fusión en src/main/java/com/homebanking/grupo13/mappers/TransferMapper.java
Auto-fusionando src/main/java/com/homebanking/grupo13/services/TransferService.java
CONFLICTO (agregar/agregar): Conflicto de fusión en src/main/java/com/homebanking/grupo13/services/TransferService.java
Auto-fusionando src/main/resources/application.properties
CONFLICTO (agregar/agregar): Conflicto de fusión en src/main/resources/application.properties
```

### Metodo 2: (nunca falla)
1. crear una branch nueva a partir de **main** desde la interfaz de github
2. git pull y git chekcout TU-RAMA desde la consola
3. copiar todos los ficheros ahi
4. editar ficheros, cambiar *dto* por *dtos* en los imports, para no generar problemas a los compañeros
5. subir cambios a github
6. borrar la branch vieja
7. actualizar en nombre de la branch actual desde la interfaz de github

### Metodo 3:
1. Descargas el branch *prueba2* en formato .zip
2. Descomprimir en tu branch nueva
3. Las palabras magicas del comando *git*  son:   add ...  commit .. push...  y el PR final desde la interfaz de github

Por que no clonar mi rama diractamente? van a tener mi nombre y los ficheros son de tu autoria, ademas voy a borrar la rama, solo lo hice para hacer pruebas.

**Comment by Mirtyta** [comment]
bueno mis archivos no aparecen porque hice un fork
pero no te preocupes voy a hacer un a rever y deshacer mi fork asi vuelve todo entes de hacer mi pull ya!
besos
