### ISSUE TITLE
Mi rama

### ISSUE THREAD

**Issue by Mirtyta** [Grupo13SpringComision23650/ElRepositoryDelGrupo13#14]
En estos momentos estoy agregando la entidad User la cual voy a mergear a la rama main para que quede unificada pero lo unico que voy a subir es User Entity/ DTOS/ y Mapper asi la main esta unificada y podemos trabajar todos con todas las entidades, luego subo los servicios y seguire trabajando con la capa controller asi cuando este listo todo seguimos con el proyecto..

SUGERENCIA:
como hice un rollback a main, mi sugerencia es hacer una nueva coneccion a sus respectivas ramas, para ello deberan hacer un directorio nuevo en donde se conectaran nuevamente con su rama pero la main nueva tendra todas las entidades y todas estan hechas de la misma manera, les deje un video explicativo en el chat de whatsapp para les sea mas claro.
con la main con todas las entidades iguales es mas facil continuar con el trabajo de cada uno, que les parece?? escucho opiniones. :)

**Comment by admred** [comment]
Buenisimo, si te parece bien asi pues bien asi.
