### ISSUE TITLE
Se me rompieron las excepciones :ambulance: 

### ISSUE THREAD

**Issue by admred** [Grupo13SpringComision23650/ElRepositoryDelGrupo13#19]
Cuando quiero triggear algun **NotFoundException** me retorna el error en HTML! deberia ser en json.

Si alguien quiere probar alguna solucion les dejo mi codigo en mi branch *luciano*

**Comment by Mirtyta** [comment]
si es en Postman, no se que error te esta dando, pero hay que cambiarle algo al postman para que no te  muestre el html

**Comment by admred** [comment]
![postman3](https://github.com/Grupo13SpringComision23650/ElRepositoryDelGrupo13/assets/76755663/33a23c74-fdac-4fe3-9f65-0cb4e03e618d)

**Comment by admred** [comment]
Ahi lo arregle
![arrglado](https://github.com/Grupo13SpringComision23650/ElRepositoryDelGrupo13/assets/76755663/df26d314-2092-455a-9248-97b76c046deb)
