### ISSUE TITLE
8) Asignación Automática:

### ISSUE THREAD

**Issue by admred** [Grupo13SpringComision23650/ElRepositoryDelGrupo13#9]
### Nuevos cambios:
```
    8) Asignación Automática:
Se deberá asignar una cuenta automáticamente al usuario al crearse, es decir, se debe 
generar una cuenta (del tipo caja de ahorro) de forma automática y asignarse en el 
momento de la creación al usuario registrado nuevo.
```

Propuesta: en **createUser** (o createUsuario)  llamaria el metodo createAccount del service de Account, para crear una caja de ahorro en pesos (por defecto). Esto cada vez que se crea un usuario nuevo.

Esto debe estar listo para el proximo **martes 5 de diciembre** , se entrega/expone en clase.

**Comment by Mirtyta** [comment]
Hola a todos, nos ha tocado la generacion automatica!! 
creo que con ello tuvimos suerte, yo elegi la entidad User, ya genere tanto para Postman como para la vista en Thymeleaft un formulario de carga, en POSTMAN un RequestBody con Raw en formato JSon, funcionando correctamente al igual que Thymeleaft, a ese metodo le agregaremos la generacion automatica de un Account que por defecto 
 private Long id;

    @Column(name = "tipo_cuenta")
    private AccountType type;  // sera "CAJA_AHORRO_PESOS"
    private String cbu; // su CBU se generara automaticamente, un numero de 10 cifras aleatorio
    private String alias; // elegido por el usuario al momento de crear su user
    @Column(name = "monto")
    private BigDecimal amount; // se asignara automaticamente a 0 y las siguientes 2 fechas se crean automaticamente ya!
    @Column(name = "fecha_creacion")
    private LocalDateTime created_at;
    @Column(name = "fecha_modificacion")
    private LocalDateTime updated_at;

Espero les parezca bien mi idea, y si no opinen asi buscamos la mejor opcion para todos!!
